### PR TITLE
added autostart for apps and firefox with tabs

### PR DESCRIPTION
**Pull request by Lumary2**
readme also includes steps about how to autorun the script after Login on manjaro

### CODE REVIEW

**Comment by Lumary2** [comment]
Hi Suraj, the starting up of the apps+Firefox should work on any Linux distro which is capable of the execution of .sh files.
 The automatic execution of the script at a certain period in the bootup(bootup, login ... ) still needs to be configured manually. For manjaro I described it in the Readme. Should I add anything else?

**Comment by suraj-singh12** [comment]
Yes, definitely what you are adding is very useful. But it would be more meaningful to the user, if the script fires up at startup automatically, no matter what distro. 
That will be the most impressive thing and will define the usability of the script. 
For sure, `Manjaro` users will find it appealing because for them this will fire automatically on startup.

I suggest you could do a bit more research to see if that's possible.

**Comment by Lumary2** [comment]
I found tutorials for Arch Linux and Ubuntu, but I cant test them because I don't have the distros available. So I think without a test its not good to add the to the readme:

https://bbs.archlinux.org/viewtopic.php?id=86815
https://linuxconfig.org/how-to-run-script-on-startup-on-ubuntu-20-04-focal-fossa-server-desktop

**Comment by suraj-singh12** [comment]
Except for Manjaro, this sounds more like `launch multiple apps at once`
Kindly rename the `title` to suit the `script` better, so that I can merge it.

**Pull request merged**
