### PR TITLE
add2path: a tool to add directories to the PATH file

### PR DESCRIPTION
**Pull request by nga1hte**
This tool will allow directories to be easily added to the path file and run any binary or shell script from anywhere in the terminal.

### CODE REVIEW

**Comment by suraj-singh12** [comment]
Though it is a plain command written in a file, I would like to ask a few questions:

1. Adding to `$PATH` is a very uncommon thing, so where would this script be useful in the daily needs of a user?
2. If a user needs to add a directory to `$PATH`, then he/she will have to place the `script` in that directory or somewhere in the reachable range, it's not accessible globally `(the script)`.
3. If a user adds something to `$PATH` accidentally and/or wishes to remove it, then how would he/she remove the `directory` from `$PATH`?

**Comment by nga1hte** [comment]
Addressing your queries.  
1. Adding to path is kind of common when you want to run some scripts or binaries globally. For example, if you have downloaded java compiler, you want it to be available globally so that you can use the javac binary in any folder.
2. The script adds itself to the path upon installation, so you can run it from any directory, making it globally accessible. So you can add any directory to the path just by running the name of the script
3. To remove the directory form the path, the user can edit the ~/.bashrc file and delete the lines added at the bottom.

**Comment by suraj-singh12** [comment]
Mention Point 3 in your README too.

**Comment by nga1hte** [comment]
Updated README to reflect removal of PATH as instruction

**Comment by suraj-singh12** [comment]
Merged!

**Pull request merged**
