### PR TITLE
Create tomonitor.sh

### PR DESCRIPTION
**Pull request by sadityakumar9211**
Enables monitor mode in wifi adapters like TP Link wn821n V2/V3

### CODE REVIEW

**Comment by suraj-singh12** [comment]
Could you quote an example where the user would need to explicitly set `the wifi` card to monitor mode?

Also, as and when a tool/software which requires wifi to be in monitor mode is executed/launched, it handles this thing automatically, and on close, disables the monitor mode too!

Could you quote some use cases of your script?

**Comment by sadityakumar9211** [comment]
Monitor mode, or RFMON (Radio Frequency MONitor) mode, allows a computer with a wireless network interface controller (WNIC) to monitor all traffic received on a wireless channel. The integrated wifi cards in the laptop/PC don't allow you to set monitor mode for security reasons. So, penetration testers use separate wifi adapters attached via USB to their laptops/PC to monitor and capture packets which integrated adapters don't allow. 

To switch to the monitor mode in these dedicated wifi adapters, you have to write a bunch of commands in the terminal. This script simplifies that process and lets you switch to monitor mode instantly. 

You can read more about monitor mode [here](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiBk8Dd8fL6AhV9T2wGHe30DN0QFnoECAgQAw&url=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FMonitor_mode%23%3A~%3Atext%3DMonitor%2520mode%252C%2520or%2520RFMON%2520(Radio%2Creceived%2520on%2520a%2520wireless%2520channel.&usg=AOvVaw1o8CYA2KaOQyf2sRYQrBgz)

**Comment by suraj-singh12** [comment]
Seems good.
Could you add a counter script, i.e. a script that turns off the monitor mode?
Because if a user prefers using your script to turn the monitor mode ON, then they would expect one to turn it OFF too.

**Comment by sadityakumar9211** [comment]
Hey @suraj-singh12 I have added the counter script i.e. the tomanaged.sh script which turns off the monitor mode and turns on the managed mode in the wifi adapters. I hope this closes #32 .

**Pull request merged**
